# Configurazione Database
database:
  type: "mysql"
  host: "localhost"
  port: 3306
  name: "litelogins"
  username: "root"
  password: "password"
  table_prefix: "lg_"

  pool_size: 10
  connection_timeout: 30000

# Impostazioni generali
settings:
  password_min_length: 6

prefix: "&8[&5LiteLogins&8] &r"