# Configurazione Database
# Tipi supportati: mysql, mariadb
database:
  type: "mysql"
  host: "localhost"
  port: 3306
  name: "litelogins"
  username: "root"
  password: "password"
  table_prefix: "lg_"

  # Impostazioni avanzate del Pool di connessioni
  pool:
    size: 10
    connection_timeout: 30000

# Impostazioni generali
settings:
  password_min_length: 6